[server]
headless = true
runOnSave = false
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#c8ff00"
backgroundColor = "#0a0a14"
secondaryBackgroundColor = "#161624"
textColor = "#ffffff"